In [1]:
import numpy as np

### Задание 1

In [2]:
print("Результат:", np.flip(np.arange(10)))

Результат: [9 8 7 6 5 4 3 2 1 0]


### Задание 2

In [3]:
mtx = np.diag(np.flip(np.arange(5)))

print(mtx)
print()
print("Сумма элементов по диагонали:", np.trace(mtx))

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]

Сумма элементов по диагонали: 10


### Задание 3

In [4]:
coef = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
res = np.array([4, 12, -3])

roots = np.linalg.solve(coef, res)

print(f"x = {round(roots[0], 2)}, y = {round(roots[1], 2)}, z = {round(roots[2], 2)}")

x = 0.47, y = 3.84, z = -5.56


### Задание 4

In [5]:
def find_similar_coef(a, b):
    norms = np.linalg.norm(a) * np.linalg.norm(b)
    return round(np.dot(a, b) / norms, 2)


users_stats = np.array([
    [2, 1, 0, 0, 0, 0],
    [1, 1, 2, 1, 0, 0],
    [2, 0, 1, 0, 0, 0],
    [1, 1, 2, 1, 0, 1],
    [0, 0, 1, 2, 0, 0],
    [0, 0, 0, 0, 0, 5],
    [1, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 3],
    [1, 0, 0, 2, 1, 4]
], np.int32)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

most_similar_user = -1
most_similar_coef = 0
for user_id, user_stats in enumerate(users_stats):
    cur_coef = find_similar_coef(user_stats, next_user_stats)
    if cur_coef > most_similar_coef:
        most_similar_coef = cur_coef
        most_similar_user = user_id + 1

print()
print("ID самого похожего пользователя:", most_similar_user)


ID самого похожего пользователя: 8
